name: strava-analysis-tool
channels:
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cffi=1.14.0=py38h7a1dbc1_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py38_0
  - cryptography=2.9.2=py38h7a1dbc1_0
  - curl=7.67.0=h2a8f88b_0
  - cycler=0.10.0=py38_0
  - expat=2.2.5=he025d50_0
  - fiona=1.8.4=py38h22081e2_0
  - freetype=2.9.1=ha9979f8_1
  - freexl=1.0.5=hfa6e2cd_0
  - gdal=2.3.3=py38hdf43c64_0
  - geopandas=0.6.1=py_0
  - geos=3.7.1=h33f27b4_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.9=py_1
  - intel-openmp=2020.1=216
  - jpeg=9b=hb83a4c4_2
  - kealib=1.4.7=h07cbb95_6
  - kiwisolver=1.2.0=py38h74a9793_0
  - krb5=1.16.4=hc04afaa_0
  - libboost=1.67.0=hd9e427e_4
  - libcurl=7.67.0=h2a8f88b_0
  - libgdal=2.3.3=h10f50ba_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libspatialite=4.3.0a=hc36aec2_19
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.9=h464c3ec_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h64f37c6_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.0.15=py38h14836fe_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - munch=2.5.0=py_0
  - numpy=1.18.1=py38h93ca92e_0
  - numpy-base=1.18.1=py38hc3f5095_1
  - openssl=1.1.1g=he774522_0
  - pandas=1.0.3=py38h47e9c7a_0
  - pcre=8.43=ha925a31_0
  - pip=20.0.2=py38_3
  - proj4=5.2.0=ha925a31_1
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.7=py_0
  - pyproj=1.9.6=py38h6782396_0
  - pyqt=5.9.2=py38ha925a31_4
  - pysocks=1.7.1=py38_0
  - python=3.8.3=he1778fa_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.23.0=py38_0
  - rtree=0.9.4=py38h21ff451_1
  - scipy=1.4.1=py38h9439919_0
  - seaborn=0.10.1=py_0
  - setuptools=46.4.0=py38_0
  - shapely=1.6.4=py38h222a598_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h2a8f88b_1
  - tk=8.6.8=hfa6e2cd_0
  - toml=0.10.0=pyh91ea838_0
  - tornado=6.0.4=py38he774522_1
  - urllib3=1.25.8=py38_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - wheel=0.34.2=py38_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_0
  - xerces-c=3.2.2=ha925a31_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.3.7=h508b16e_0
  - pip:
    - polyline==1.4.0
prefix: C:\Users\Felix\Anaconda3\envs\strava-analysis-tool

